Feature/monorepo
tributech-solutions/tributech-catalog-api pull request #37
Opened 2021-11-16 08:26 UTC by mayrmax

2021-11-16 08:30 UTC, mayrmax commented on apps/tributech-catalog/src/models/parsed-models.ts
> +// import { ContextType, EnumValue, MapKey, SelfDescription } from './models';
remove file

2021-11-16 08:33 UTC, mayrmax commented on libs/core/src/lib/validation-errors/validation-error.component.html
> +  <!--  <tt-icon-->
rem

2021-11-19 08:17 UTC, chlumper requested changes
It's really difficult to review such a huge PR which also contains a lot of renaming's and re-formatting.
I tried to focus one some important parts/files only.

2021-11-19 08:17 UTC, chlumper commented on docker-compose.run.yml
> +      - '80:80'
We should maybe use a different exposed port than `80` for the catalog-ui since it's "in use" at many systems.
Or is there a reason behind it?

2021-11-19 08:17 UTC, chlumper commented on apps/tributech-catalog-ui/Dockerfile
> +FROM node:16-alpine As build
We should add a `.dockerignore` file.
see e.g. "9. Keeping unnecessary files out of your Node.js Docker images" at https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/ for example and explanation.

2021-11-19 08:17 UTC, chlumper commented on apps/tributech-catalog/Dockerfile
>  FROM node:16-alpine As base
We should add a `.dockerignore` file.
see e.g. "9. Keeping unnecessary files out of your Node.js Docker images" at https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/ for example and explanation.

2021-11-19 08:17 UTC, chlumper commented on nx.json
> +        "accessToken": "N2Q0N2E4N2QtZGE3MS00OWIyLTg4ZDctZGJmNmU1OWFmYmMzfHJlYWQtd3JpdGU="
What kind of access token is this?
Should most likely be provided with a secret!?

2021-11-19 08:17 UTC, chlumper commented on apps/tributech-catalog/Dockerfile
> +RUN apk --no-cache add git
Can you please explain why we need git in the build container?

2021-11-19 08:29 UTC, mayrmax commented on apps/tributech-catalog-ui/src/assets/config/config.json
> +    "identityServerUrl": "https://auth.dev.dataspace-hub.com/auth/realms",
not easily as this would need other adaptions

2021-11-19 08:31 UTC, mayrmax commented on docker-compose.run.yml
> +      - '80:80'
ngnix default port

2021-11-19 08:32 UTC, mayrmax commented on apps/tributech-catalog-ui/Dockerfile
> +FROM node:16-alpine As build
thats why i use a build image and a final image, i need a lot of files what would you exclude?

2021-11-19 08:33 UTC, mayrmax commented on nx.json
> +        "accessToken": "N2Q0N2E4N2QtZGE3MS00OWIyLTg4ZDctZGJmNmU1OWFmYmMzfHJlYWQtd3JpdGU="
token for nx-cloud (distributed caching) i dot thnik its an issue to have this public

2021-11-19 08:33 UTC, mayrmax commented on apps/tributech-catalog/Dockerfile
> +RUN apk --no-cache add git
for calculation of the affected projects/libraries through nx

2021-11-19 08:49 UTC, chlumper commented on docker-compose.run.yml
> +      - '80:80'
I'm talking about the published/exposed port (aka the left hand side) not the internal port of the container.
https://docs.docker.com/compose/compose-file/compose-file-v3/#ports

2021-11-19 08:51 UTC, chlumper commented on apps/tributech-catalog-ui/Dockerfile
> +FROM node:16-alpine As build
Even if you use a multistage build this still affects local builds. I would use the example from the link above as a starting point.

2021-11-19 08:55 UTC, chlumper commented on apps/tributech-catalog-ui/src/assets/config/config.json
> +    "identityServerUrl": "https://auth.dev.dataspace-hub.com/auth/realms",
okay i guess we have to life with it.

what's the general concept for the future? i guess it should be configurable from within the catalog-ui at some point?
it would be great if you can but it on the agenda.

2021-11-19 09:17 UTC, chlumper commented on nx.json
> +        "accessToken": "N2Q0N2E4N2QtZGE3MS00OWIyLTg4ZDctZGJmNmU1OWFmYmMzfHJlYWQtd3JpdGU="
as discussed in a call we need a long term strategy for none "demo" access tokens.
it's okay for me if we keep it FOR NOW if there is no easy way around.

2021-11-19 09:35 UTC, mayrmax commented on apps/tributech-catalog/Dockerfile
>  FROM node:16-alpine As base
basic docker ignore is present at root

2021-11-19 09:38 UTC, chlumper approved these changes
Thx for integrating feedback!

2021-11-19 09:47 UTC, merged